In [101]:
import os
import csv
import pandas as pd
import numpy as np
from mprod import table2tensor
from mprod.dimensionality_reduction import TCAM


# reading in the txt data table
npc = int(3)
ss = str(int(1))
jj = str(int(9))
# obtain meta data and otu table
file_path = 'simdata/sim'+ss+'_ntime'+jj+'.csv'
data_table = pd.read_csv(file_path, usecols=lambda col: col != 'delivery', \
              dtype={'month':int, 'studyid':str})
data_table = data_table.iloc[:, 2:]
data_table = data_table.sample(n=100)
data_table = data_table.set_index(['studyid', 'month'])
data_table

,,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V943,V944,V945,V946,V947,V948,V949,V950,V951,V952
studyid,month,,,,,,,,,,,,,,,,,,,,,
7,7,20811,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,5,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,9,0,0,9589,0,0,0,0,2638,10249,0,...,0,0,0,0,0,0,0,0,0,0
35,3,17097,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,3,13472,0,0,0,0,0,2805,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,2,8,0,20039,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,6,13,0,0,0,0,9,0,0,9,0,...,0,0,0,0,0,0,0,0,0,0
30,9,0,0,0,0,0,0,0,972,0,0,...,0,0,0,0,0,0,0,0,0,0
27,4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,4,0,0,0,0,554,0,636,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [98]:
# format into data tensor
data_tensor, map1, map3 =  table2tensor(data_table)

In [99]:


# run TCAM
tca = TCAM()
tca_trans = tca.fit_transform(data_tensor)

# save results
tca_df = pd.DataFrame(tca_trans)
tca_df.rename(index = dict(map(reversed, map1.items())), inplace = True)   
tca_df.iloc[:,:3]

               0             1             2
1  -11713.671369   -209.440997 -15758.249789
4   38220.205624  -5031.568559  32826.927014
7    8222.697995  11678.066502    485.506158
9  -19067.652273  -6328.827006  -9925.878068
10   9595.617755  -5355.856908   3198.391904
12  22292.605727  -1934.101200  -4410.252440
14 -16414.717297  -9805.585928   -325.952468
16  19264.065790  -7272.638031    839.205816
17   6731.555517  -3549.554508 -29463.495427
20  11379.898621   4582.631805   9768.968201
22   5148.243809  16836.074995  16076.137873
25 -21364.060951 -10856.077669  -7018.484697
27   6991.598254  -6065.643984  16272.490418
30  -8593.656797 -19380.395368  -4072.082748
31 -22447.570206 -16061.739174  -7323.778612
35 -17041.058532  33633.107923 -18591.762644
38 -19733.749791  26086.268900  -2949.847274
41  -1288.757564  21194.079302   6414.265169
42 -12611.424064  -1647.285865  -4953.557432
43  -1570.118414  -8649.894497  -3676.746901
44  44958.866790    721.092353  20678.365373
46 -20958.918623 -12582.712086   1909.830576

{0: '1',
 1: '4',
 2: '7',
 3: '9',
 4: '10',
 5: '12',
 6: '14',
 7: '16',
 8: '17',
 9: '20',
 10: '22',
 11: '25',
 12: '27',
 13: '30',
 14: '31',
 15: '35',
 16: '38',
 17: '41',
 18: '42',
 19: '43',
 20: '44',
 21: '46'}

In [67]:
# create a sample dataframe
df = pd.DataFrame({'A': [1, 1, 2, 2], 'B': ['x', 'y', 'x', 'y'], 'C': [10, 20, 30, 40]})

# set columns 'A' and 'B' as the index levels
df = df.set_index(['A', 'B'])

# display the resulting dataframe
print(df)

      C
A B
1 x  10
  y  20
2 x  30
  y  40

In [72]:
file_path= "/Users/pixushi/Library/CloudStorage/Box-Box/0-ftsvd/version0/data/Schirmer2018/Schirmer2018.tsv"

data_table = pd.read_csv(file_path, index_col=[0,1], sep="\t", dtype={'Week':int})
data_table = data_table.loc[:,data_table.median() > 1e-7]
data_table.shape
data_table

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Lachnospiraceae-g__-s__-OTU_975306  \
SubjectID Week
P_10343   0                                              0.000869
          4                                              0.020421
          12                                             0.006230
          52                                             0.002211
P_10897   0                                              0.077260
...                                                           ...
P_9687    52                                             0.038399
P_9872    0                                              0.021931
          4                                              0.000404
          12                                             0.002116
          52                                             0.016309

                k__Bacteria-p__Bacteroidetes-c__Bacteroidia-o__Bacteroidales-f__Porphyromonadaceae-g__Parabacteroides-s__distasonis-OTU_585914  \
SubjectID Week
P_10343   0                                              0.022900
          4                                              0.000000
          12                                             0.000049
          52                                             0.000000
P_10897   0                                              0.000863
...                                                           ...
P_9687    52                                             0.006944
P_9872    0                                              0.000000
          4                                              0.000000
          12                                             0.000000
          52                                             0.000000

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__-g__-s__-OTU_352304  \
SubjectID Week
P_10343   0                                              0.000033
          4                                              0.000823
          12                                             0.000997
          52                                             0.000291
P_10897   0                                              0.017448
...                                                           ...
P_9687    52                                             0.000511
P_9872    0                                              0.002625
          4                                              0.005252
          12                                             0.000163
          52                                             0.000655

                k__Bacteria-p__Firmicutes-c__Erysipelotrichi-o__Erysipelotrichales-f__Erysipelotrichaceae-g__.Eubacterium-.s__dolichum-OTU_539581  \
SubjectID Week
P_10343   0                                              0.001304
          4                                              0.000092
          12                                             0.006262
          52                                             0.000048
P_10897   0                                              0.005751
...                                                           ...
P_9687    52                                             0.001634
P_9872    0                                              0.000000
          4                                              0.000000
          12                                             0.004775
          52                                             0.000154

                k__Bacteria-p__Firmicutes-c__Erysipelotrichi-o__Erysipelotrichales-f__Erysipelotrichaceae-g__Holdemania-s__-OTU_367215  \
SubjectID Week
P_10343   0                                              0.000401
          4                                              0.001555
          12                                             0.002387
          52                                             0.005875
P_10897   0                                              0.004280
...                                                           ...
P_9687    52                                             0.000204
P_9872    0                                              0.000000
          4                                              0.003905
          12                                             0.000868
          52                                             0.000058

                k__Bacteria-p__Actinobacteria-c__Actinobacteria-o__Bifidobacteriales-f__Bifidobacteriaceae-g__Bifidobacterium-s__-OTU_997439  \
SubjectID Week
P_10343   0                                              0.000468
          4                                              0.056469
          12                                             0.107378
          52                                             0.049600
P_10897   0                                              0.025000
...                                                           ...
P_9687    52                                             0.006127
P_9872    0                                              0.007961
          4                                              0.040937
          12                                             0.070400
          52                                             0.032657

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Ruminococcaceae-g__Ruminococcus-s__-OTU_591635  \
SubjectID Week
P_10343   0                                              0.001706
          4                                              0.001317
          12                                             0.000981
          52                                             0.001420
P_10897   0                                              0.000643
...                                                           ...
P_9687    52                                             0.000511
P_9872    0                                              0.000065
          4                                              0.000000
          12                                             0.000760
          52                                             0.003050

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Veillonellaceae-g__Veillonella-s__parvula-OTU_518743  \
SubjectID Week
P_10343   0                                              0.000000
          4                                              0.000000
          12                                             0.000065
          52                                             0.000016
P_10897   0                                              0.000059
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.001453
          4                                              0.000000
          12                                             0.000000
          52                                             0.000019

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__-g__-s__-OTU_191043  \
SubjectID Week
P_10343   0                                              0.001304
          4                                              0.000000
          12                                             0.000000
          52                                             0.000097
P_10897   0                                              0.000034
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.000260
          4                                              0.000000
          12                                             0.000000
          52                                             0.000000

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__-g__-s__-OTU_509416  \
SubjectID Week
P_10343   0                                              0.000100
          4                                              0.040550
          12                                             0.047451
          52                                             0.001259
P_10897   0                                              0.019545
...                                                           ...
P_9687    52                                             0.014502
P_9872    0                                              0.031996
          4                                              0.001212
          12                                             0.002632
          52                                             0.058065

                ...  \
SubjectID Week  ...
P_10343   0     ...
          4     ...
          12    ...
          52    ...
P_10897   0     ...
...             ...
P_9687    52    ...
P_9872    0     ...
          4     ...
          12    ...
          52    ...

                k__Bacteria-p__Firmicutes-c__Erysipelotrichi-o__Erysipelotrichales-f__Erysipelotrichaceae-g__Bulleidia-s__moorei-OTU_851938  \
SubjectID Week
P_10343   0                                              0.000000
          4                                              0.000146
          12                                             0.000131
          52                                             0.000323
P_10897   0                                              0.000000
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.000000
          4                                              0.000135
          12                                             0.000109
          52                                             0.000116

                k__Bacteria-p__Firmicutes-c__Erysipelotrichi-o__Erysipelotrichales-f__Erysipelotrichaceae-g__-s__-OTU_145801  \
SubjectID Week
P_10343   0                                              0.005384
          4                                              0.000000
          12                                             0.000474
          52                                             0.000371
P_10897   0                                              0.000524
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.000000
          4                                              0.000000
          12                                             0.000027
          52                                             0.000019

                k__Bacteria-p__Actinobacteria-c__Actinobacteria-o__Bifidobacteriales-f__Bifidobacteriaceae-g__Bifidobacterium-s__-OTU_553611  \
SubjectID Week
P_10343   0                                              0.000000
          4                                              0.000000
          12                                             0.000000
          52                                             0.000016
P_10897   0                                              0.000025
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.000000
          4                                              0.000000
          12                                             0.000054
          52                                             0.000019

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Ruminococcaceae-g__Faecalibacterium-s__prausnitzii-OTU_365842  \
SubjectID Week
P_10343   0                                              0.028827
          4                                              0.000421
          12                                             0.017021
          52                                             0.006037
P_10897   0                                              0.005768
...                                                           ...
P_9687    52                                             0.061581
P_9872    0                                              0.040825
          4                                              0.002424
          12                                             0.001248
          52                                             0.003219

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Lachnospiraceae-g__Blautia-s__-OTU_1078587  \
SubjectID Week
P_10343   0                                              0.000468
          4                                              0.032260
          12                                             0.027028
          52                                             0.000452
P_10897   0                                              0.042745
...                                                           ...
P_9687    52                                             0.000715
P_9872    0                                              0.006074
          4                                              0.007541
          12                                             0.003174
          52                                             0.010641

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Lachnospiraceae-g__Lachnospira-s__-OTU_843553  \
SubjectID Week
P_10343   0                                              0.000000
          4                                              0.000384
          12                                             0.000049
          52                                             0.000000
P_10897   0                                              0.011993
...                                                           ...
P_9687    52                                             0.023080
P_9872    0                                              0.000000
          4                                              0.000269
          12                                             0.000434
          52                                             0.000135

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Lachnospiraceae-g__-s__-OTU_363400  \
SubjectID Week
P_10343   0                                              0.001003
          4                                              0.003550
          12                                             0.026718
          52                                             0.000517
P_10897   0                                              0.028265
...                                                           ...
P_9687    52                                             0.011744
P_9872    0                                              0.002625
          4                                              0.000404
          12                                             0.009848
          52                                             0.002795

                k__Bacteria-p__Actinobacteria-c__Actinobacteria-o__Bifidobacteriales-f__Bifidobacteriaceae-g__Bifidobacterium-s__-OTU_484304  \
SubjectID Week
P_10343   0                                              0.000000
          4                                              0.000055
          12                                             0.000441
          52                                             0.000113
P_10897   0                                              0.000203
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.000065
          4                                              0.000269
          12                                             0.000488
          52                                             0.000096

                k__Bacteria-p__Firmicutes-c__Clostridia-o__Clostridiales-f__Ruminococcaceae-g__Faecalibacterium-s__prausnitzii-OTU_174403  \
SubjectID Week
P_10343   0                                              0.000000
          4                                              0.000000
          12                                             0.000327
          52                                             0.000032
P_10897   0                                              0.000085
...                                                           ...
P_9687    52                                             0.002042
P_9872    0                                              0.000239
          4                                              0.000000
          12                                             0.000000
          52                                             0.000058

                k__Bacteria-p__Bacteroidetes-c__Bacteroidia-o__Bacteroidales-f__Bacteroidaceae-g__Bacteroides-s__-OTU_364926
SubjectID Week
P_10343   0                                              0.026586
          4                                              0.000000
          12                                             0.009304
          52                                             0.019595
P_10897   0                                              0.000000
...                                                           ...
P_9687    52                                             0.000000
P_9872    0                                              0.013319
          4                                              0.002289
          12                                             0.000515
          52                                             0.000810

[348 rows x 114 columns]

In [73]:
data_table.rename(columns= {k:f"Fature_{e+1}" for e,k in enumerate(data_table.columns)}, inplace=True) 
data_table.shape
data_table

                Fature_1  Fature_2  Fature_3  Fature_4  Fature_5  Fature_6  \
SubjectID Week
P_10343   0     0.000869  0.022900  0.000033  0.001304  0.000401  0.000468
          4     0.020421  0.000000  0.000823  0.000092  0.001555  0.056469
          12    0.006230  0.000049  0.000997  0.006262  0.002387  0.107378
          52    0.002211  0.000000  0.000291  0.000048  0.005875  0.049600
P_10897   0     0.077260  0.000863  0.017448  0.005751  0.004280  0.025000
...                  ...       ...       ...       ...       ...       ...
P_9687    52    0.038399  0.006944  0.000511  0.001634  0.000204  0.006127
P_9872    0     0.021931  0.000000  0.002625  0.000000  0.000000  0.007961
          4     0.000404  0.000000  0.005252  0.000000  0.003905  0.040937
          12    0.002116  0.000000  0.000163  0.004775  0.000868  0.070400
          52    0.016309  0.000000  0.000655  0.000154  0.000058  0.032657

                Fature_7  Fature_8  Fature_9  Fature_10  ...  Fature_105  \
SubjectID Week                                           ...
P_10343   0     0.001706  0.000000  0.001304   0.000100  ...    0.000000
          4     0.001317  0.000000  0.000000   0.040550  ...    0.000146
          12    0.000981  0.000065  0.000000   0.047451  ...    0.000131
          52    0.001420  0.000016  0.000097   0.001259  ...    0.000323
P_10897   0     0.000643  0.000059  0.000034   0.019545  ...    0.000000
...                  ...       ...       ...        ...  ...         ...
P_9687    52    0.000511  0.000000  0.000000   0.014502  ...    0.000000
P_9872    0     0.000065  0.001453  0.000260   0.031996  ...    0.000000
          4     0.000000  0.000000  0.000000   0.001212  ...    0.000135
          12    0.000760  0.000000  0.000000   0.002632  ...    0.000109
          52    0.003050  0.000019  0.000000   0.058065  ...    0.000116

                Fature_106  Fature_107  Fature_108  Fature_109  Fature_110  \
SubjectID Week
P_10343   0       0.005384    0.000000    0.028827    0.000468    0.000000
          4       0.000000    0.000000    0.000421    0.032260    0.000384
          12      0.000474    0.000000    0.017021    0.027028    0.000049
          52      0.000371    0.000016    0.006037    0.000452    0.000000
P_10897   0       0.000524    0.000025    0.005768    0.042745    0.011993
...                    ...         ...         ...         ...         ...
P_9687    52      0.000000    0.000000    0.061581    0.000715    0.023080
P_9872    0       0.000000    0.000000    0.040825    0.006074    0.000000
          4       0.000000    0.000000    0.002424    0.007541    0.000269
          12      0.000027    0.000054    0.001248    0.003174    0.000434
          52      0.000019    0.000019    0.003219    0.010641    0.000135

                Fature_111  Fature_112  Fature_113  Fature_114
SubjectID Week
P_10343   0       0.001003    0.000000    0.000000    0.026586
          4       0.003550    0.000055    0.000000    0.000000
          12      0.026718    0.000441    0.000327    0.009304
          52      0.000517    0.000113    0.000032    0.019595
P_10897   0       0.028265    0.000203    0.000085    0.000000
...                    ...         ...         ...         ...
P_9687    52      0.011744    0.000000    0.002042    0.000000
P_9872    0       0.002625    0.000065    0.000239    0.013319
          4       0.000404    0.000269    0.000000    0.002289
          12      0.009848    0.000488    0.000000    0.000515
          52      0.002795    0.000096    0.000058    0.000810

[348 rows x 114 columns]

In [74]:
data_tensor, map1, map3 =  table2tensor(data_table)

from mprod.dimensionality_reduction import TCAM

tca = TCAM()
tca_trans = tca.fit_transform(data_tensor)

In [75]:
from sklearn.decomposition import PCA

pca = PCA()
pca_trans = pca.fit_transform(data_table)

In [76]:
tca_loadings = tca.mode2_loadings  # Obtain TCAM loadings
pca_loadings = pca.components_     # Obtain PCA loadings

tca_var = tca.explained_variance_ratio_*100 # % explained variation per TCA factor
pca_var = pca.explained_variance_ratio_*100 # % explained variation per TCA factor

tca_df = pd.DataFrame(tca_trans)   # Cast TCA scores to dataframe
tca_df.rename(index = dict(map(reversed, map1.items()))
              , inplace = True)    # use the inverse of map1 to denote each row 
                                   # of the TCAM scores with it's subject ID
    
pca_df = pd.DataFrame(pca_trans)   # Cast PCA scores to dataframe
pca_df.index = data_table.index    # anotate PC scores with sample names

In [50]:
tca_loadings[:, :3]
tca_loadings.shape

(114, 347)

In [49]:
data_tensor.shape

(87, 114, 4)

In [78]:
tca_df.iloc[:, :3]

                0         1         2
P_10343  0.079388 -0.035552 -0.024487
P_10897  0.086418 -0.206863  0.064296
P_1108  -0.112244  0.033006 -0.006913
P_11085  0.163604 -0.251573  0.068796
P_11369  0.131169  0.092731 -0.271362
...           ...       ...       ...
P_9473  -0.121741  0.079591  0.062084
P_9563   0.135490  0.081923  0.113657
P_9658   0.131857 -0.097206 -0.024868
P_9687  -0.086933 -0.007824  0.055681
P_9872   0.003868 -0.093529  0.065065

[87 rows x 3 columns]